# Generated by Django 2.2.1 on 2019-05-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('det', models.CharField(choices=[('I', 'Interes'), ('R', 'Regiune')], default='N/A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regiune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='Nevalidat', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AddField(
            model_name='point',
            name='regiune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Regiune'),
        ),
    ]
